ics_ghana_media_platform_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
]

#This is used for
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

post/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import profile, edit_profile
from . import views as user_views

from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView
)
from django.urls import reverse_lazy

urlpatterns = [
    path('', views.home, name="home"),
    path('trending/', views.trending, name="trending"),
    path('newevent/', views.newEvent, name="newevent"),
    path('localnews/', views.localnews, name="localnews"),
    path('membership/', views.membership, name="membership"),
    path('internationalnews/', views.internationalnews, name="internationalnews"),
    path('article/', views.article, name="article"),
    path('technologicalnews/', views.technologicalnews, name="technologicalnews"),
    path('newEvent/<int:id>', views.detail_newEvent, name="detailed_newEvent"),
    path('detail/<int:id>/', views.detail_page, name="detailed_page"),
    path('trendings/<int:id>/', views.trending_detailed_page, name="trending_detailed_page"),
    path('internationalnewsDetail/<int:id>/', views.InternationNewsDetailedPage, name="internationalnewsDetail"),
    path('technologicalNewsDetailPage/<int:id>/', views.technologicalNewsDetailPage, name="technologicalNewsDetailPage"),
    path('localnewsdetailedpage/<int:id>/', views.localnewsdetailedpage, name="localnewsdetailedpage"),
    path('articleDetailedPage/<int:id>/', views.articleDetailedPage, name="articleDetailedPage"),
    path("register/", views.register, name="register"),
    
    
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('profile/<username>/', profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    
    path('password_change/', PasswordChangeView.as_view(template_name='password_change.html',success_url=reverse_lazy('password_change_done')),name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='password_change_done.html'),name='password_change_done'),

]

post/forms.py
from django import forms
from .models import Comment, InternationalNewsComment, TechnologicalNewsComment, LocalNewsComment, ArticlesComment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TimeInput(attrs={'class':'input', 'placeholder':'Enter Comment'}),required=False)
    
    class Meta:
        model = Comment
        fields = ['body', 'user', 'post']
        

class InternationalNewsCommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TimeInput(attrs={'class':'input', 'placeholder':'Enter Comment'}),required=False)
    
    class Meta:
        model = InternationalNewsComment
        fields = ['body', 'user', 'post']
        
        
class ArticlesCommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TimeInput(attrs={'class':'input', 'placeholder':'Enter Comment'}),required=False)
    
    class Meta:
        model = ArticlesComment
        fields = ['body', 'user', 'post']
        
  
class TechnologicalNewsCommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TimeInput(attrs={'class':'input', 'placeholder':'Enter Comment'}),required=False)
    
    class Meta:
        model = TechnologicalNewsComment
        fields = ['body', 'user', 'post'] 
        
class LocalNewsCommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TimeInput(attrs={'class':'input', 'placeholder':'Enter Comment'}),required=False)
    
    class Meta:
        model = LocalNewsComment
        fields = ['body', 'user', 'post']  
    
    
#registration form
class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


#Update profile form
class EditProfileForm(forms.Form):
    username = forms.CharField()
    about_me = forms.CharField(widget=forms.Textarea())
    image = forms.ImageField(required=False)
    
    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def clean_username(self):
        """
        This function throws an exception if the username has already been 
        taken by another user
        """

        username = self.cleaned_data['username']
        if username != self.original_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'A user with that username already exists.')
        return username

templates/article.html
{% extends 'base.html' %}
{% load static %}
   {% block content %}
      <!-- Videos Section -->
      <div class="videos">
        <h1></h1>
        <div class="videos__container">
          <!-- Single Video starts -->
          {% for post in post_items %}
          <div class="video">
            <div class="video__thumbnail">
              <a href="{% url 'articleDetailedPage' post.id %}"><img src="{{ post.picture.url }}" alt="" /></a>
            </div>
            <div class="video__details">
              <div class="author">
                <img
                  src="{{ post.picture.url }}"
                  alt=""
                />
              </div>
              <div class="title">
                <h3> <a href="{% url 'articleDetailedPage' post.id %}"> {{post.title}}</a></h3>
                 <pre><b><a href="{% url 'articleDetailedPage' post.id %}"> {{post.user.username}}, {{post.likes}} likes </a></b></pre>
                 {% comment %} <pre><b>{% for tag in post.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></pre> {% endcomment %}
                <pre> <b>{{post.posted}}</b></pre>
              </div>
            </div>
          </div>

          {% endfor %}
          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Material Icons -->

    <link rel="stylesheet" href=" https://fonts.googleapis.com/icon?family=Material+Icons" />

    <!-- CSS File -->
    <link rel="stylesheet" href={% static 'styles.css'%} />
    <title>{% block head_title %}{% endblock head_title %}</title>
  </head>
  <body>

    {% if user.is_authenticated %}
    <!-- Header Starts -->
    <div class="header">
      <div class="header__left">
        <i id="menu" class="material-icons">menu</i>
        <img
          src={% static 'images/mainlogo.jpg'%}
          alt=""
        />
      </div>

      <div class="header__search">
        <form action="">
          <input type="text" placeholder="Search" aria-label="Search" name="search" type="search" />
          <button><i class="material-icons">search</i></button>
        </form>
      </div>

      <div class="header__icons">
        <i class="material-icons display-this">search</i>
        <i class="material-icons">videocam</i>
        <i class="material-icons">apps</i>
        <i class="material-icons">notifications</i>
        
        <a href="{% url 'profile' request.user.username %}"
        class="nav-item nav-link {% if request.user.username in request.path %}active{% endif %}">
        <i class="material-icons display-this">account_circle</i>
        </a>
      </div>
    </div>
    <!-- Header Ends -->

    <!-- Main Body Starts -->
    <div class="mainBody">
      <!-- Sidebar Starts -->
      <div class="sidebar">
        <div class="sidebar__categories">
          <div class="sidebar__category">
            <i class="material-icons">waving_hand</i>
            <span>Welcome {{ user.username }}</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">event</i>
            <span><a style="text-decoration:none; color: rgb(96, 96, 96);" href="{% url 'newevent' %}">New Event</a></span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">feed</i>
            <span><a style="text-decoration:none; color: rgb(96, 96, 96);" href="{% url 'internationalnews' %}">International News</a></span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">trending_up</i>
            <span><a style="text-decoration:none; color: rgb(96, 96, 96);" href="{% url 'trending' %}">Trending</a></span>
          </div>
        </div>
        <hr />
        <div class="sidebar__categories">
          <div class="sidebar__category">
            <i class="material-icons">newspaper</i>
            <span><a style="text-decoration:none; color: rgb(96, 96, 96);" href="{% url 'technologicalnews' %}">Technological News</a></span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">feed</i>
            <span><a style="text-decoration:none; color: rgb(96, 96, 96);" href="{% url 'localnews' %}">Local News</a></span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">remember_me</i>
            <span>Membership</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">article</i>
            <span><a style="text-decoration:none; color: rgb(96, 96, 96);" href="{% url 'article' %}">Articles</a></span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">api</i>
            <span>Developers</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">opacity</i>
            <span>Investors</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">art_track</i>
            <span> Artists</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">verified</i>
            <span>Advertisement</span>
          </div>
          <div class="sidebar__category">
            <i class="material-icons">logout</i>
            <span><a style="text-decoration:none; color: rgb(96, 96, 96);" href="{% url 'logout' %}">Logout?</a></span>
          </div>

        </div>
        <hr />
      </div>
      <!-- Sidebar Ends -->
      {% else %}
        <div class="alert alert-success" role="alert">
            <h3>Welcome!</h3>
            <a href="{% url 'register' %}">Signup</a>
            <a href="{% url 'login' %}">Login</a>
        </div>
      {% endif %}



    {% block content %}
    {% endblock content %}

    <script src={% static 'index.js'%}></script>
    <!-- Main Body Ends -->
  </body>
</html>

templates/detail_page.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}

     

      <!-- Videos Section -->
     <div class="detailPage_videos">
        <div class="detailPage_videos__container">
          <!-- Single Video starts -->
            <div class="detailPage_video">
                <div class="detailPage_video__thumbnail">
                <img src="{{ detailed_page.picture.url }}" alt="" />
                </div>
                <div class="video__details">
                    <div class="detailPage_author">
                        <img
                        src="{{ detailed_page.picture.url }}"
                        alt=""
                        />
                    </div>
                    <div class="detailPage_title">
                        <h3> <a href=""> {{ detailed_page.title }}</a></h3>
                        <h2><b>{% for tag in detailed_page.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></h2>
                        <h2><b><a href=""> {{detailed_page.user.username}}, {{detailed_page.likes}} likes </a></b></h2>
                        <form method="POST">
                          {% csrf_token %}
                          <input type="text" required name="body"/>

                          <button type="submit">Post HERE</button>
                        </from>
                        <h2> <b> <a href="">{{detailed_page.posted}}</a> </b></h2><br>
                        <h4> <a href=""> {{ detailed_page.caption }}</a></h4>
                        {% for comment in comments %}
                          {{comment.body}}
                          {{comment.user.username}}
                        {% endfor %}
                    </div>
                    

                </div>
            </div>

          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}

templates/edit_profile.html
<!-- templates/users/edit_profile.html -->
{% extends 'base.html' %}

{% block head_title %}Edit profile{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <h2 class="my-5">Edit profile</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ form.username.label_tag }}
          <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
            name="username" value='{{ form.username.value|default:user.username }}'>
          {% if form.username.errors %}
          <div class="invalid-feedback">{{ form.username.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.about_me.label_tag }}
          <textarea type="text" class="form-control {% if form.about_me.errors %}is-invalid{% endif %}" id="id_about_me"
            name="about_me" value='{{ form.about_me.value }}' rows="5"></textarea>
          {% if form.about_me.errors %}
          <div class="invalid-feedback">{{ form.about_me.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.image.label_tag }}<br>
          <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
            accept="image/*">
          {% if form.image.errors %}
          <div class="invalid-feedback">{{ form.image.errors }}</div>
          {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <br>
    </div>
  </div>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}


      <!-- Videos Section -->
      <div class="videos">
        <h1></h1>

        <div class="videos__container">
          <!-- Single Video starts -->
          {% for post in post_items %}

          <div class="video">
            <div class="video__thumbnail">
              <a href="{% url 'detailed_page' post.id %}"><img src="{{ post.picture.url }}" alt="" /></a>
            </div>
            <div class="video__details">
              <div class="author">
                <img
                  src="{{ post.picture.url }}"
                  alt=""
                />
              </div>
              <div class="title">
                <h3> <a href="{% url 'detailed_page' post.id %}"> {{post.title}}</a></h3>
                 <pre><b><a href="{% url 'detailed_page' post.id %}"> {{post.user.username}}, {{post.likes}} likes </a></b></pre>
                 {% comment %} <pre><b>{% for tag in post.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></pre> {% endcomment %}
                <pre> <b>{{post.posted}}</b></pre>
              </div>
            </div>
          </div>

          {% endfor %}
          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}

templates/int_detail_page.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}

     

      <!-- Videos Section -->
     <div class="detailPage_videos">
        <div class="detailPage_videos__container">
          <!-- Single Video starts -->
            <div class="detailPage_video">
                <div class="detailPage_video__thumbnail">
                <img src="{{ detailed_page.picture.url }}" alt="" />
                </div>
                <div class="video__details">
                    <div class="detailPage_author">
                        <img
                        src="{{ detailed_page.picture.url }}"
                        alt=""
                        />
                    </div>
                    <div class="detailPage_title">
                        <h3> <a href=""> {{ detailed_page.title }}</a></h3>
                        <h2><b>{% for tag in detailed_page.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></h2>
                        <h2><b><a href=""> {{detailed_page.user.username}}, {{detailed_page.likes}} likes </a></b></h2>
                        <form method="POST">
                          {% csrf_token %}
                          <input type="text" required name="body"/>

                          <button type="submit">Post HERE</button>
                        </from>
                        <h2> <b> <a href="">{{detailed_page.posted}}</a> </b></h2><br>
                        <h4> <a href=""> {{ detailed_page.caption }}</a></h4>
                        {% for comment in comments %}
                        <hr style="width:200px;">
                        {{comment.user.username}} : {{comment.body}}
                          
                        {% endfor %}
                    </div>
                    

                </div>
            </div>

          <!-- Single Video Ends here -->


          
        </div>
      </div>
    </div>
   
   {% endblock content %}

   

templates/internationalnews.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}


      <!-- Videos Section -->
      <div class="videos">
        <h1></h1>

        <div class="videos__container">
          <!-- Single Video starts -->
          {% for post in post_items %}

          <div class="video">
            <div class="video__thumbnail">
              <a href="{% url 'internationalnewsDetail' post.id %}"><img src="{{ post.picture.url }}" alt="" /></a>
            </div>
            <div class="video__details">
              <div class="author">
                <img
                  src="{{ post.picture.url }}"
                  alt=""
                />
              </div>
              <div class="title">
                <h3> <a href="{% url 'internationalnewsDetail' post.id %}"> {{post.title}}</a></h3>
                 <pre><b><a href="{% url 'internationalnewsDetail' post.id %}"> {{post.user.username}}, {{post.likes}} likes </a></b></pre>
                 {% comment %} <pre><b>{% for tag in post.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></pre> {% endcomment %}
                <pre> <b>{{post.posted}}</b></pre>
              </div>
            </div>
          </div>

          {% endfor %}
          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}

templates/localnews.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}


      <!-- Videos Section -->
      <div class="videos">
        <h1></h1>

        <div class="videos__container">
          <!-- Single Video starts -->
          {% for post in post_items %}

          <div class="video">
            <div class="video__thumbnail">
              <a href="{% url 'localnewsdetailedpage' post.id %}"><img src="{{ post.picture.url }}" alt="" /></a>
            </div>
            <div class="video__details">
              <div class="author">
                <img
                  src="{{ post.picture.url }}"
                  alt=""
                />
              </div>
              <div class="title">
                <h3> <a href="{% url 'localnewsdetailedpage' post.id %}"> {{post.title}}</a></h3>
                 <pre><b><a href="{% url 'localnewsdetailedpage' post.id %}"> {{post.user.username}}, {{post.likes}} likes </a></b></pre>
                 {% comment %} <pre><b>{% for tag in post.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></pre> {% endcomment %}
                <pre> <b>{{post.posted}}</b></pre>
              </div>
            </div>
          </div>

          {% endfor %}
          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}

templates/login.html
<h3>login</h3>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>{{ field.label }}: <br> {{ field }}</p>
    {% endfor %}
    <button type="submit">Login</button>
</form>

<p>Don't have an account? <a href="{% url 'register' %}">Signup here</a></p>

templates/membership.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="about-container">
    <div id="about-container1">
        <h1><a href="http://cridad.com"target="_blank">Bigger Companies</a> </h1>
        <p><a href="http://cridad.com"target="_blank">Save 73%</a> </p>
        <p><a href="http://cridad.com"target="_blank">Yearly: &#8373;4000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Quarterly: &#8373;2000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Montly: &#8373;1000</a> </p>
        <p>Discounted from <strike>7000/yr.</strike></p>
        <p>Discounted from <strike>5000/Qr.</strike></p>
        <p>Discounted from <strike>3000/mo.</strike></p>
        <h2><a href="http://cridad.com"target="_blank">Get Plan</a> </h2>
    </div>
    <div id="about-container1">
        <h1><a href="http://cridad.com"target="_blank">Mid Size Companies</a> </h1>
        <p><a href="http://cridad.com"target="_blank">Save 73%</a> </p>
        <p><a href="http://cridad.com"target="_blank">Yearly: &#8373;4000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Quarterly: &#8373;2000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Montly: &#8373;1000</a> </p>
        <p>Discounted from <strike>7000/yr.</strike></p>
        <p>Discounted from <strike>5000/Qr.</strike></p>
        <p>Discounted from <strike>3000/mo.</strike></p>
        <h2><a href="http://cridad.com"target="_blank">Get Plan</a> </h2>
    </div>
    <div id="about-container1">
        <h1><a href="http://cridad.com"target="_blank">Smaller Companies</a> </h1>
        <p><a href="http://cridad.com"target="_blank">Save 73%</a> </p>
        <p><a href="http://cridad.com"target="_blank">Yearly: &#8373;4000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Quarterly: &#8373;2000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Montly: &#8373;1000</a> </p>
        <p>Discounted from <strike>7000/yr.</strike></p>
        <p>Discounted from <strike>5000/Qr.</strike></p>
        <p>Discounted from <strike>3000/mo.</strike></p>
        <h2><a href="http://cridad.com"target="_blank">Get Plan</a> </h2>
    </div>
    <div id="about-container1">
        <h1><a href="http://cridad.com"target="_blank">Individuals</a> </h1>
        <p><a href="http://cridad.com"target="_blank">Save 73%</a> </p>
        <p><a href="http://cridad.com"target="_blank">Yearly: &#8373;4000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Quarterly: &#8373;2000</a> </p>
        <p><a href="http://cridad.com"target="_blank">Montly: &#8373;1000</a> </p>
        <p>Discounted from <strike>7000/yr.</strike></p>
        <p>Discounted from <strike>5000/Qr.</strike></p>
        <p>Discounted from <strike>3000/mo.</strike></p>
        <h2><a href="http://cridad.com"target="_blank">Get Plan</a> </h2>
    </div>
</div>

{% endblock content %}

templates/new_event_detailed_page.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}

     

      <!-- Videos Section -->
     <div class="detailPage_videos">
        <div class="detailPage_videos__container">
          <!-- Single Video starts -->
            <div class="detailPage_video">
                <div class="detailPage_video__thumbnail">
                <img src="{{ neventdetail.picture.url }}" alt="" />
                </div>
                <div class="video__details">
                    <div class="detailPage_author">
                        <img
                        src="{{ neventdetail.picture.url }}"
                        alt=""
                        />
                    </div>
                    <div class="detailPage_title">
                        <h3> <a href=""> {{ neventdetail.title }}</a></h3>
                        <h2><b>{% for tag in neventdetail.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></h2>
                        <h2><b><a href=""> {{neventdetail.user.username}}, {{neventdetail.likes}} likes </a></b></h2>
                        <h2> <b> <a href="">{{neventdetail.posted}}</a> </b></h2><br>
                        <h4> <a href=""> {{ neventdetail.caption }}</a></h4>
                    </div>
                </div>
            </div>

          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}

templates/newevent.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}


      <!-- Videos Section -->
      <div class="videos">
        <h1></h1>

        <div class="videos__container">
          <!-- Single Video starts -->
          {% for newevent in newEvent_items %}

          <div class="video">
            <div class="video__thumbnail">
              <a href="{% url 'detailed_newEvent' newevent.id %}"><img src="{{ newevent.picture.url }}" alt="" /></a>
            </div>
            <div class="video__details">
              <div class="author">
                <img
                  src="{{ newevent.picture.url }}"
                  alt=""
                />
              </div>
              <div class="title">
                <h3> <a href="{% url 'detailed_newEvent' newevent.id %}"> {{newevent.title}}</a></h3>
                 <pre><b><a href="{% url 'detailed_newEvent' newevent.id %}"> {{newevent.user.username}}, {{newevent.likes}} likes </a></b></pre>
                 {% comment %} <pre><b>{% for tag in post.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></pre> {% endcomment %}
                <pre> <b>{{newevent.posted}}</b></pre>
              </div>
            </div>
          </div>

          {% endfor %}
          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}

templates/password_change.html
{% extends 'base.html' %}

{% block head_title %}Change password{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-7">
      <h2 class=" my-5">Change password</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.old_password.label_tag }}
          <input type="password" class="form-control {% if form.old_password.errors %}is-invalid{% endif %}"
            id="id_old_password" name="old_password" value='{{ form.old_password.value|default:"" }}'>
          {% if form.old_password.errors %}
          <div class="invalid-feedback">{{ form.old_password.errors }}</div>
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.new_password1.label_tag }}
          <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
            id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>
          {% if form.new_password1.errors %}
          <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
          {% endif %}
          <small class="text-muted">{{ form.new_password1.help_text }}</small>
        </div>
        <div class="form-group">
          {{ form.new_password2.label_tag }}
          <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
            id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>
          {% if form.new_password2.errors %}
          <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Change password</button>
    </div>
  </div>
</div>
{% endblock content %}

templates/technologicalnews.html
{% extends 'base.html' %}
{% load static %}

   {% block content %}


      <!-- Videos Section -->
      <div class="videos">
        <h1></h1>

        <div class="videos__container">
          <!-- Single Video starts -->
          {% for post in post_items %}

          <div class="video">
            <div class="video__thumbnail">
              <a href="{% url 'technologicalNewsDetailPage' post.id %}"><img src="{{ post.picture.url }}" alt="" /></a>
            </div>
            <div class="video__details">
              <div class="author">
                <img
                  src="{{ post.picture.url }}"
                  alt=""
                />
              </div>
              <div class="title">
                <h3> <a href="{% url 'technologicalNewsDetailPage' post.id %}"> {{post.title}}</a></h3>
                 <pre><b><a href="{% url 'technologicalNewsDetailPage' post.id %}"> {{post.user.username}}, {{post.likes}} likes </a></b></pre>
                 {% comment %} <pre><b>{% for tag in post.tag.all%}<a href="{{tag.get_absolute_url}}"> #{{tag}} </a><br>{% endfor %}</b></pre> {% endcomment %}
                <pre> <b>{{post.posted}}</b></pre>
              </div>
            </div>
          </div>

          {% endfor %}
          <!-- Single Video Ends here -->
        </div>
      </div>
    </div>
   
   {% endblock content %}